apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{.Release.Name}}-postgres-{{.Values.algorand.network}}
  labels:
    app: {{.Release.Name}}-postgres
    {{- include "algon.selectorLabels" . | nindent 4 }}
    {{- include "algon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: {{.Release.Name}}-postgres
    {{- include "algon.labels" . | nindent 4 }}
    {{- include "algon.selectorLabels" . | nindent 4 }}

