{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-stack
  name: {{ include "algon.fullname" . }}-servicemonitor
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "algon.fullname" . }}
{{- end }}
