{{- $fullName := include "algon.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap    #{{ $fullName }}
data:
{{ (.Files.Glob "config/config.json").AsConfig | indent 2 }}

---

{{- if eq .Values.script "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-starts-script
data:
{{ (.Files.Glob "scripts/start_all.sh").AsConfig | indent 2 }}
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-indexer-script
data:
{{ (.Files.Glob "scripts/run_indexer.sh").AsConfig | indent 2 }}
