{{- $fullName := include "algon.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: algon-configmap    #{{ $fullName }}
data:
{{ (.Files.Glob "config/config.json").AsConfig | indent 2 }}
