apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{.Release.Name}}-postgres-{{.Values.algorand.network}}
  labels:
    app: algo-postgres
    network: {{.Values.algorand.network}}
    release: {{.Release.Name}}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: algo-postgres
    network: {{.Values.algorand.network}}
    release: {{.Release.Name}}
