apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "algon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: https
    - name: metrics
      protocol: TCP
      port: 81
      targetPort: 9100
  selector:
    {{- include "algon.selectorLabels" . | nindent 4 }}
