apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-service
  labels:
    app: {{.Chart.Name}}
    network: {{.Values.algorand.network}}
    release: {{.Release.Name}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080 #{{ .Values.service.port }}
      targetPort: 8080    
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
    - name: indexer
      protocol: TCP
      port: 8980
      targetPort: 8980
  selector:
    app: {{.Chart.Name}}
    network: {{.Values.algorand.network}}
    release: {{.Release.Name}}
