apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "algon.fullname" . }}
  labels:
    {{- include "algon.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "algon.fullname" . }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "algon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "algon.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: algon-data-pv-claim
        - name: config-volume
          configMap:
            name: algon-configmap
      serviceAccountName: {{ include "algon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: ALGORAND_DATA
              value: /algorand/node/data
            - name: ALGORAND_NETWORK
              value:  {{ .Values.algorand.network }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./algod", "-d", "data"]
          # command: ["./goal", "node", "start", "-p", "r1.algorand.network:4161;r2.algorand.network:4161"]
          # command: [ "/bin/bash" ]
          # tty: true
          # stdin: true
          
          volumeMounts:
            - mountPath: "/algorand/node/data"
              name: data-volume
            - mountPath: /root/node/data/config.json
              subPath: config.json
              name: config-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        {{- if .Values.Probe.enabled }}
          readinessProbe:
            tcpSocket:
              port: 9100
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 9100
            initialDelaySeconds: 300
            periodSeconds: 60
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
