apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }} 
  labels:
    network: {{.Values.algorand.network}}
spec:
  serviceName: {{ .Release.Name }}-service
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{.Chart.Name}} # has to match .spec.template.metadata.labels
      release: {{.Release.Name}}
      network: {{.Values.algorand.network}}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{.Chart.Name}}
        release: {{.Release.Name}}
        network: {{.Values.algorand.network}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pv-claim
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-configmap
      {{ if eq .Values.script "enabled" }}
        - name: script-volume
          configMap:
            name: {{ .Release.Name }}-starts-script
      {{ end }}
        - name: script-indexer
          configMap:
            name: {{ .Release.Name }}-indexer-script
        - name: {{.Release.Name}}-postgres-secrets
          secret:
            items:
            - key: postgres_password
              path: postgres_password
            - key: postgres_user
              path: postgres_user
            - key: postgres_db
              path: postgres_db
            secretName: {{.Release.Name}}-postgres-secrets
      serviceAccountName: {{ include "algon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      # hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: ALGORAND_DATA
              value: "/algorand/node/data/"
            - name: ALGORAND_NETWORK
              value:  {{ .Values.algorand.network }}
            # - name: PATH
            #   value: "/root/node:$PATH"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

      {{ if eq .Values.algorand.network "testnet" }}
          image: "{{ .Values.image.testnet.repository }}:{{ .Values.image.testnet.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if eq .Values.script "enabled" }}
          command: ["sh"]
          args: ["/scripts-dir/start_all.sh"]
        {{ end }}
        {{ if eq .Values.script "disabled" }}
          command: ["/root/node/algod", "-d", "/algorand/node/data"]
        {{ end }}
          # command: ["./goal", "node", "start", "-p", "r1.algorand.network:4161;r2.algorand.network:4161"]
          # command: [ "/bin/bash" ]
          # tty: true
          # stdin: true
      {{- end }}

      {{ if eq .Values.algorand.network "mainnet" }}
          image: "{{ .Values.image.mainnet.repository }}:{{ .Values.image.mainnet.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if eq .Values.script "enabled" }}
          command: ["sh"]
          args: ["/scripts-dir/start_all.sh"]
        {{ end }}
        {{ if eq .Values.script "disabled" }}
          command: ["/root/node/algod", "-d", "/algorand/node/data"]
        {{ end }}
          # command: ["./goal", "node", "start", "-p", "r1.algorand.network:4161;r2.algorand.network:4161"]
          # command: [ "/bin/bash" ]
          # tty: true
          # stdin: true
      {{- end }}
      
      {{ if eq .Values.algorand.network "betanet" }}
          image: "{{ .Values.image.mainnet.repository }}:{{ .Values.image.mainnet.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if eq .Values.script "enabled" }}
          command: ["sh"]
          args: ["/scripts-dir/start_all.sh"]
        {{ end }}
        {{ if eq .Values.script "disabled" }}
          command: ["/root/node/algod", "-d", "/algorand/node/data"]
        {{ end }}
          # command: ["./goal", "node", "start", "-p", "r1.algorand.network:4161;r2.algorand.network:4161"]
          # command: [ "/bin/bash" ]
          # tty: true
          # stdin: true
      {{- end }}
      
      {{ if eq .Values.algorand.network "mule" }}
          image: "{{ .Values.image.mainnet.repository }}:{{ .Values.image.mainnet.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if eq .Values.script "enabled" }}
          command: ["sh"]
          args: ["/scripts-dir/start_all.sh"]
        {{ end }}
        {{ if eq .Values.script "disabled" }}
          command: ["/root/node/algod", "-d", "/algorand/node/data"]
        {{ end }}
          # command: ["./goal", "node", "start", "-p", "r1.algorand.network:4161;r2.algorand.network:4161"]
          # command: [ "/bin/bash" ]
          # tty: true
          # stdin: true
      {{- end }}
     
          volumeMounts:
            - mountPath: /algorand/node/
              name: data-volume
            - mountPath: /algorand/node/data/config.json
              subPath: config.json
              name: config-volume
        {{ if eq .Values.script "enabled" }}
            - mountPath: /scripts-dir
              name: script-volume
        {{- end }}

          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9100
              protocol: TCP
        {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: 8080 #9100
            initialDelaySeconds: 30
            periodSeconds: 30
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080 #9100
            initialDelaySeconds: 300
            periodSeconds: 60
        {{- end }}

        - name: indexer
          env:
            - name: ALGORAND_DATA
              value: "/algorand/node/data/"
            - name: ALGORAND_NETWORK
              value: {{ .Values.algorand.network }}
            - name: POSTGRES_HOST
              value: {{.Release.Name}}-postgres-{{.Values.algorand.network}}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "v8hlDV0yMAHHlIurYupj"
            - name: DATABASE_NAME
              value: "cexplorer"
            - name: SSL_MODE
              value: disable
            - name: METRICS_MODE
              value: "ON"
            - name: ALGORAND_HOST
              value: {{ .Release.Name }}-service
            - name: ALGORAND_PORT
              value: "8080"
          image: bvvovk/algorandindexer:1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["sh"]
          # args: ["/scripts-dir/run_indexer.sh"]
          command: [ "/bin/bash" ]
          tty: true
          stdin: true
          volumeMounts:
            - mountPath: /var/run/secrets
              name: {{.Release.Name}}-postgres-secrets
              readOnly: true
            - mountPath: /algorand/node/
              name: data-volume
            - mountPath: /scripts-dir
              name: script-indexer
          ports:
            - name: indexer
              containerPort: 8980
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
